name: Ghostferry tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Starting up MySQL
        run: .github/workflows/start-mysql.sh

      - name: Running Golang tests
        run: make test-go
  ruby-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: "true"
      BUNDLE_WITHOUT: "development"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Starting up MySQL
        run: .github/workflows/start-mysql.sh

      - name: Running Ruby tests
        run: DEBUG=1 bundle exec ruby test/main.rb -v -n "InterruptResumeTest#test_interrupt_resume_idempotence_with_writes_to_source"

